import type { Metadata } from 'next';
import { Rubik, Rubik_Mono_One } from 'next/font/google';
import './globals.css';

const rubik = Rubik({
  weight: ['400', '500'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-rubik',
});

const rubikMonoOne = Rubik_Mono_One({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-rubik-mono-one',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
